### ISSUE TITLE
How to use with worker-loader?

### ISSUE THREAD

**Issue by michaltakac** [AlvaroBernalG/event-worker#2]
https://github.com/webpack-contrib/worker-loader

**Comment by AlvaroBernalG** [comment]
Hi @michaltakac Apologies for the huge response delay. When you opened this issue I was under extreme pressure with barely time to have a look at your request. Are you still looking for a solution ??

**Comment by michaltakac** [comment]
Hi @AlvaroBernalG, not looking for solution anymore since at Decentraland we completely reinvented our architecture. I barely remember that I was trying to find information on how to use worker loader to bundle workers made with `event-worker`, but came up with some custom solution. Anyways, that was a way back and that code was discarded long ago :D.
